version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_HOST: '127.0.0.1:3306'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./scripts/mysql:/docker-entrypoint-initdb.d
      - ./mysqldata:/var/lib/mysql
